pipeline {
    agent any
    stages {
         stage('checkout') {
            steps {
                // Checkout the code
                git branch: 'main', changelog: false, poll: false, url: 'https://github.com/Nagavamshia/Jenkins-Zero-To-Hero.git'
            }
        }
        stage('Build') {
            steps {
                // Compile the Java code
                sh 'javac HelloWorld.java'
            }
        }

        stage('Run') {
            steps {
                // Execute the compiled Java program
                sh 'java HelloWorld'
            }
        }
    }
}
