pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                // Compile the Java code
                sh 'javac HelloWorld.java'
            }
        }

        stage('Run') {
            steps {
                // Execute the compiled Java program
                sh 'java HelloWorld'
            }
        }
    }
}
